Starcoder.Msg.PLAYER_SHAPE = 'forme de jouer';
Starcoder.Msg.TREE_SPREAD = 'arbre propagation';
Starcoder.Msg.TREE_SCALE = "échelle de l'arbre";
Starcoder.Msg.TREE_BRANCH_FACTOR = "facteur de branche d'arbre";
Starcoder.Msg.TREE_BRANCH_DECAY = "branche d'arbre décroissance";
Starcoder.Msg.TREE_DEPTH = "profondeur de l'arbre";
Starcoder.Msg.SHIP_COLOR = "couleur du vaisseau";
Starcoder.Msg.MAGNITUDE = 'ampleur';
Starcoder.Msg.ANGLE = 'angle';
Starcoder.Msg.CREATE = 'créer';
Starcoder.Msg.RADIUS = 'rayon';
Starcoder.Msg.VELOCITY = 'vélocité';
Starcoder.Msg.WARP = 'warp';
Starcoder.Msg.EVERY = 'chaque';
Starcoder.Msg.SECONDS = 'secondes';
Starcoder.Msg.UNTIL = "jusqu'à";
Starcoder.Msg.DO = 'faire';
Starcoder.Msg.ORB = 'orbe';
Starcoder.Msg.PLANETOID = 'planetoid'