Starcoder.Msg.PLAYER_SHAPE = 'player shape';
Starcoder.Msg.TREE_SPREAD = 'tree spread';
Starcoder.Msg.TREE_SCALE = 'tree scale';
Starcoder.Msg.TREE_BRANCH_FACTOR = 'tree branch factor';
Starcoder.Msg.TREE_BRANCH_DECAY = 'tree branch decay';
Starcoder.Msg.TREE_DEPTH = 'tree depth';
Starcoder.Msg.SHIP_COLOR = 'ship color';
Starcoder.Msg.MAGNITUDE = 'magnitude';
Starcoder.Msg.ANGLE = 'angle';
Starcoder.Msg.CREATE = 'create';
Starcoder.Msg.RADIUS = 'radius';
Starcoder.Msg.VELOCITY = 'velocity';
Starcoder.Msg.WARP = 'warp';
Starcoder.Msg.EVERY = 'every';
Starcoder.Msg.SECONDS = 'seconds';
Starcoder.Msg.UNTIL = 'until';
Starcoder.Msg.DO = 'do';
Starcoder.Msg.ORB = 'orb';
Starcoder.Msg.PLANETOID = 'planetoid'